### ISSUE TITLE
sync or replicate function not defined?

### ISSUE THREAD

**Issue by ozexpert** [nolanlawson/pouchdb-adapter-cordova-sqlite#1]
After using cordova-sqlite adapter, i get error when calling,, sync or replicate.from() function.

```
    this.localDB.sync(this.remoteDB, {
      live: true,
      retry: true
    });
```

i get error like this:
```
this.localDB.sync is not a function. (In 'this.localDB.sync(this.remoteDB, {
            live: true,
            retry: true
        })', 'this.localDB.sync' is undefined)
```

localDB is just this
```
this.localDB = new PouchDB('dbname', { adapter: 'cordova-sqlite'});
```

happens on both android and ios

**Comment by nolanlawson** [comment]
It looks like you are using a custom build of PouchDB and did not include the `pouchdb-replication` plugin. Is that right?

**Comment by ozexpert** [comment]
`pouchdb-replication` i'm not using this, but was working with websql before. and what do you mean by custom build of pouchDB? i got from your repo. 

Am i suppose to use `pouchdb-replication` plugin? I'll try..

**Comment by nolanlawson** [comment]
Hm, I thought maybe you were using Custom Builds: https://pouchdb.com/custom.html. That is a very strange bug, and I'm not sure what's going on. Do you have some sample code to reproduce?

**Comment by ozexpert** [comment]
my code is very simple

```
let localDB = new PouchDB('tag', { adapter: 'cordova-sqlite'});
let remoteDB = new PouchDB('https://mydomain.com/tag', {adapter: 'https'});
localDB.sync(remoteDB, {
      live: true,
      retry: true
    });
```

simple?

**Comment by ozexpert** [comment]
OOooops, sorry i should have mentioned this 
I'm using this plugin in cordova
https://github.com/driftyco/cordova-plugin-wkwebview-engine

```
2016-08-23 20:03:06.317 MyProject[44611:4124285] ERROR: Unhandled Promise rejection: this.localDB.sync is not a function. (In 'this.localDB.sync(this.remoteDB, {
                live: true,
                retry: true
            })', 'this.localDB.sync' is undefined) ; Zone: <root> ; Task: Promise.then ; Value: TypeError: this.localDB.sync is not a function. (In 'this.localDB.sync(this.remoteDB, {
                live: true,
                retry: true
            })', 'this.localDB.sync' is undefined)
```

**Comment by ozexpert** [comment]
any news? my ios app is just blocked.

**Comment by nolanlawson** [comment]
I'm sorry, I don't have time to look at this right now. I have no idea why this wouldn't be working. Does it only not work in iOS, or in Android too?

**Comment by nolanlawson** [comment]
I am unable to reproduce. A lot of folks seemed to have trouble figuring out how to include this in a new project, so I added some additional instructions and a full demo app to the README: https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite#usage

Please reopen if this doesn't solve your problem.
