### ISSUE TITLE
Problem when use require('pouchdb-adapter-cordova-sqlite');

### ISSUE THREAD

**Issue by tiagoMaua** [nolanlawson/pouchdb-adapter-cordova-sqlite#10]
Hi!

 Hi have this problem when use this code: 

 require is not native in javascript. So i used this method from cordova.

`PouchDB.plugin(cordova.require('pouchdb-adapter-cordova-sqlite'));`

Error: module pouchdb-adapter-cordova-sqlite not found

My environment: 

Ionic         : version 1.7.13
Cordova   : version 6.0.0
Npm         : version 2.14.9
Node        : version v0.12.9
Ionic CLI  : 1.7.13

**Comment by nolanlawson** [comment]
The README assumes you're using `require()` via Browserify/Webpack. You should follow the directions for "unpkg" instead (i.e. just download the prebuilt file and don't use `require()`). Hope that helps!
