### ISSUE TITLE
No response from db.get()

### ISSUE THREAD

**Issue by sashagrunge** [nolanlawson/pouchdb-adapter-cordova-sqlite#2]
I got a problem use the adapter, the database created successfully but db.get('id') has no response, no callback no promise

**Comment by nolanlawson** [comment]
Can you provide a test case to reproduce? Note that you will also need the `cordova-plugin-sqlite-2` installed.

**Comment by nolanlawson** [comment]
I am unable to reproduce. A lot of folks seemed to have trouble figuring out how to include this in a new project, so I added some additional instructions and a full demo app to the README: https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite#usage

Please reopen if this doesn't solve your problem.
