### ISSUE TITLE
Fallback to WebSQL when plugin unavailable

### ISSUE THREAD

**Issue by Bouzmine** [nolanlawson/pouchdb-adapter-cordova-sqlite#4]
I use PouchDB on an Ionic project and it's awesome. With version 6, I'm not able to run my app in the browser because when setting database's adapter to `cordova-sqlite` it just says the plugin can't be found. I'd like it to fallback to `WebSQL` on browser like it did on version 5.

**Comment by nolanlawson** [comment]
You can do something like this:

```js
PouchDB.plugin(require('pouchdb-adapter-cordova-sqlite'));
var db;
if (window.cordova) {
  db = new PouchDB('db', {adapter: 'cordova-sqlite'});
} else {
  db = new PouchDB('db');
}
```

Alternatively, you can build one version for Cordova and one version for the web.

I'm sorry for the inconvenience but it was just incredibly difficult to maintain two uses for the codebase within PouchDB core. We ran into tons of bugs and confusion over it. Thanks for understanding.
