### ISSUE TITLE
Add package to Bower

### ISSUE THREAD

**Issue by marc-ed-raffalli** [nolanlawson/pouchdb-adapter-cordova-sqlite#5]
Very cool stuff and nicely documented !

One thing though, the package is not available on Bower, any plan for it ?

BR, Marc

**Comment by nolanlawson** [comment]
From now on I am not supporting Bower for any of my projects. If you need Bower support I recommend just downloading the file from unpkg.com and including it in your projects that way (or via a script tag). See https://github.com/unpkg/npm-http-server#bower-support for more details; basically the whole JS ecosystem is moving away from Bower right now.

**Comment by marc-ed-raffalli** [comment]
I worked around it in my gulp build, no trouble. It was to highlight it as the other package were on Bower.
