### ISSUE TITLE
Type Definitions

### ISSUE THREAD

**Issue by withinsight** [nolanlawson/pouchdb-adapter-cordova-sqlite#7]
When specifying the iosDatabaseLocation property, the TypeScript compiler borks:

<img width="401" alt="borkandbindy" src="https://cloud.githubusercontent.com/assets/740056/19577199/27798346-96e4-11e6-811c-72e85f76c7f8.png">

**Comment by nolanlawson** [comment]
This is a bug in the PouchDB type definitions, which are managed at DefinitelyTyped: http://definitelytyped.org/. You'll need to make a correction there, or to make a change in your own typescript definitions to support this.
